// SPDX-Licence-Identifier: EUPL-1.2

// Package opencode owns the lthn-side surface for OpenCode
// (opencode.ai) — the open-source coding agent we run sandboxed
// via go-process + a containerised lthn/dev:latest image, surfaced
// to clients via the reverse-proxy mount at
// /v1/api/sandbox/<id>/* on coreapi.Engine.
//
// Discipline: container lifecycle goes through dappco.re/go/process
// (long-running daemons get Start, not Run). Persistence consumes
// dappco.re/go/orm as a library (stateless intent bridge) — callers
// declare a Schema() on the record type and use orm.Of[T](c) at call
// sites; orm is not registered as a Core service. Reverse-proxy
// mirrors the pkg/plugin pattern — one RouteGroup registered at boot,
// targets map mutates as sandboxes Start / Stop.
//
// Usage example:
//
//	c := core.New(core.WithName("opencode", opencode.NewService(opencode.Options{})))
//	svc := core.MustServiceFor[*opencode.Service](c, "opencode")
//	r := svc.Start()                      // spawns container, returns ID
//	id := r.Value.(string)
//	// curl http://localhost:8000/v1/api/sandbox/<id>/global/health
package opencode

import (
	core "dappco.re/go"
	"dappco.re/go/orm"
)

// Sandbox is the record for one running opencode-serve container.
// Persisted via orm so the registry survives lthn restarts (resume
// by re-attaching to docker containers still alive).
//
// Container name is derived: "lthn-opencode-" + ID — used for
// docker stop / rm without needing to persist it separately.
//
// Usage example:
//
//	sb := opencode.Sandbox{ID: "oc-7f3a2b1c", Image: "lthn/dev:latest", Status: opencode.StatusRunning}
type Sandbox struct {
	// ID is the sandbox identifier surfaced in the reverse-proxy URL
	// /v1/api/sandbox/<id>/*. Generated by Start() — short opaque
	// string with the "oc-" prefix.
	ID string

	// Image is the OCI tag the container was spawned from. v1
	// hard-codes lthn/dev:latest; future per-bundle Spawn() lets
	// callers override.
	Image string

	// HostPort is the dynamically-allocated host port mapped to the
	// container's :4096 (opencode serve's default). The reverse-proxy
	// forwards to http://127.0.0.1:<HostPort>/.
	HostPort int

	// Status is one of StatusRunning / StatusStopped / StatusFailed.
	// Mutates over the sandbox lifetime; Start writes Running, Stop
	// writes Stopped, error paths write Failed.
	Status string

	// CreatedAt is the spawn timestamp. Useful for housekeeping
	// (drop sandboxes older than N days, etc.) but not load-bearing
	// for the v1 protocol surface.
	CreatedAt core.Time
}

// containerPrefix is the canonical name prefix for lthn-owned
// opencode-serve containers. Reconcile() filters docker output on
// this prefix to identify which containers to recover after a
// serve restart.
const containerPrefix = "lthn-opencode-"

// ContainerName returns the docker container name for a given
// sandbox ID. Deterministic so callers don't need to persist it
// separately — `docker stop lthn-opencode-<id>` always finds the
// right container.
//
// Usage example:
//
//	name := opencode.ContainerName("oc-1735843891234")
//	// → "lthn-opencode-oc-1735843891234"
func ContainerName(id string) string {
	return containerPrefix + id
}

// Schema declares the orm shape for Sandbox. Consumed by
// orm.Of[Sandbox](c) at call sites — the orm bridge introspects
// the Schema() method to produce intent the Medium executes.
//
// Usage example:
//
//	// At a Sandbox-using call site:
//	r := orm.Of[Sandbox](c).Find("oc-7f3a2b1c")
//	if r.OK { sb := r.Value.(Sandbox); _ = sb.HostPort }
func (Sandbox) Schema() orm.Schema {
	return orm.Define(func(b *orm.Builder) {
		b.Name("opencode_sandboxes")
		b.PK("id")
		b.String("id").NotNull()
		b.String("image").NotNull()
		b.Int("host_port").NotNull()
		b.String("status").NotNull()
		b.Time("created_at").NotNull()
		b.Index("status")
	})
}

// Canonical Status values. Stringly typed in the schema but
// these constants are the only values the package writes.
const (
	StatusRunning = "running"
	StatusStopped = "stopped"
	StatusFailed  = "failed"
)
